Models/ErrorViewModel.cs
namespace CallSystem.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CallsController.cs
using System.Diagnostics;
using CallSystem.Models;
using Microsoft.AspNetCore.Mvc;


namespace CallSystem.Controllers
{
    public class CallsController : Controller
    {
        private readonly ILogger<CallsController> _logger;

        public CallsController(ILogger<CallsController> logger)
        {
            _logger = logger;
        }

        public IActionResult East()
        {
            return View();
        }

        public IActionResult West()
        {
            return View();
        }

     //   [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CallSystem.Models;

namespace CallSystem.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }
    
    public IActionResult Index()
    {
        
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MqttController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MQTTnet;
using MQTTnet.Client.Options;
using MQTTnet.Extensions.ManagedClient;
using CallSystem.Models;
using Newtonsoft.Json;
using System.Text;
using System.Text.Json;
namespace CallSystem.Models
{
    
    //[Route("[controller]")]
    public class Mqtt : Controller
    {
        private readonly ILogger<Mqtt> _logger;

        public Mqtt(ILogger<Mqtt> logger)
        {
            _logger = logger;
        }

        public static Dictionary<string, int> mmap = new Dictionary<string, int>()
                {  
                    {"DBCS-020", 0},
                    {"DBCS-021", 0},
                    {"DBCS-016", 0},
                    {"DBCS-017", 0},
                    {"DBCS-024", 0},
                    {"DBCS-019", 0},
                    {"DBCS-022", 0},
                    {"DBCS-023", 0},
                    {"DBCS-026", 0},
                    {"DBCS-018", 0},
                    {"DBCS-025", 0},
                    {"AFSM-001", 0},
                    {"AFSM-002", 0},
                    {"AFSM-003", 0},
                    {"AFSM-004", 0},
                    {"HOPS-001", 0},
                    {"APBS-001", 0},
                    {"HSTS-002", 0},
                    {"SPSS-001", 0},
                    {"AFCS-001", 0},
                    {"AFCS-002", 0},
                    {"AFCS-003", 0},
                    {"AFCS-004", 0},
                    {"AFCS-005", 0},
                    {"AFCS-006", 0},
                    {"AFCS-007", 0},
                    {"AFCS-008", 0},
                    {"DIOSS-004", 0},
                    {"DIOSS-008", 0},
                    {"DIOSS-007", 0},
                    {"DIOSS-006", 0},
                    {"DIOSS-005", 0},
                    {"DBCS-010", 0},
                    {"DBCS-011", 0},
                    {"DBCS-012", 0},
                    {"DBCS-013", 0},
                    {"DBCS-014", 0},
                    {"DBCS-015", 0},
                    {"HOPS-002", 0},
                    {"CIOSS-002", 0},
                    {"CIOSS-001", 0},
                    {"USS-001", 0}

                };

        public IActionResult Index()
        {  
             
             async Task MqttListener()
                {
                    string clientId = Guid.NewGuid().ToString();
                    string mqttURI = "127.0.0.1";
                    int mqttPort = 1883;

                    var options = new ManagedMqttClientOptionsBuilder()
                        .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
                        .WithClientOptions(new MqttClientOptionsBuilder()
                            .WithClientId(clientId)
                            .WithTcpServer(mqttURI, mqttPort))
                    .Build();
                    var mqttClient = new MqttFactory().CreateManagedMqttClient();
                    await mqttClient.SubscribeAsync(new MqttTopicFilterBuilder().WithTopic("maintenance/calls/+").Build());
                    await mqttClient.StartAsync(options);

                    mqttClient.UseConnectedHandler(e =>
                    {
                        Debug.WriteLine("Connected successfully with MQTT Broker.");
                    }
                    );
                    mqttClient.UseDisconnectedHandler(e =>
                    {
                        Debug.WriteLine("Disconnected from MQTT Broker.");
                    }
                    );
                    
                    mqttClient.UseApplicationMessageReceivedHandler(e =>
                    {
                        
                        
                        try
                        {
                            string topic = e.ApplicationMessage.Topic;
                            if (string.IsNullOrWhiteSpace(topic) == false)
                            
                                {
                                   var payload = e.ApplicationMessage.ConvertPayloadToString();
                                   System.Console.WriteLine($"Payload is {payload}");
                                   var deserializedJson = JsonConvert.DeserializeObject<Dictionary<string,int>>(payload);
                                   if (deserializedJson is not null)
                                   {
                                        foreach( KeyValuePair<string, int> kvp in deserializedJson)
                                   {    
                                       mmap[kvp.Key] = kvp.Value;
                                       System.Console.WriteLine($"Machine {kvp.Key} has been set to {kvp.Value}");
                                    }
                                   }
                                   
                                    

                                }
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex.Message, ex);
                        }

                    });
                }
            return View(MqttListener());
        }
        public IActionResult CallStatus()
        {              
            ViewBag.mmap = mmap;
            return View(); 
        } 
        public IActionResult CallsFormatted()
        {              
            ViewBag.mmap = mmap;
            return View(); 
        } 

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/TimeController.cs
using System.Text;
using System.Diagnostics;
using CallSystem.Models;
using Microsoft.AspNetCore.Mvc;
using MQTTnet;
using MQTTnet.Client.Options;
using MQTTnet.Extensions.ManagedClient;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using static System.Text.Json.JsonSerializer;

namespace CallSystem.Controllers
{
    public class TimeController : Controller
    {
        private readonly ILogger<TimeController> _logger;

        public TimeController(ILogger<TimeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Richmond Call System";
}

<div class="text-center">
    <h1 class="display-4">Richmond Call System</h1>
    
</div>
<div class = "main-text">
    <p>
        This is the <strong>Richmond Call System.</strong>
    </p>
    <p>
        This Call System is a .NET project, written in C#, which will run on any web server. When
        a machine is in need of a Technician, a switch is turned on at the machine which changes the graphics
        on the local web server. When a call switch is turned on, the graphic representation of that machine will 
        change colors to red and begin to flash. Any web browser, or TV in browser mode, pointed to the server,
        will display the graphic layout of the plant depicting all sorting machines.
    </p>
    <p>
        The view of the plant is split into East and West
        in order to simplify the graphics. The graphic representation of the plant is designed to be 
        viewed best in a web browser at full screen (F11). This is how the TV displays are configured 
        which are distributed on the workroom floor 
        in areas where Technicians can monitor their machines for calls. </p>
    <p>     
        Here is a screenshot of the 'West' side of the plant with DIOSS-005
        in need of Maintenance attention (the red box is flashing).
    </p>
    <div><img class="img-fluid mx-auto d-block" src="../images/call.png"></div>
    <p>
       The system uses the <a href="https://mqtt.org">MQTT messaging protocol</a> to subscribe to 'topics' 
       and listen for those messages.
    </p>
    <p>
        These messages are currently sent over a TCP/IP network by two single board PCs, one located in the East
        part of the plant and the other in the West, which monitor physical inputs
        controlled by toggle switches on each of our DBCS, DIOSS, CIOSS and AFCS letter sorting machines.
        We plan to replace the single board PC / toggle switch mechanism with 'Quuppa QT3-1' tags. The tags are part of the larger SELS sytem. 
        The SELS server will send an MQTT message when a QT3-1 button push is detected and our Call System will change
        the graphics on the webserver to indicate that the machine is in need of a Technician.
    </p>
    <p>
        We are still testing this system but believe that it should be fairly easy and inexpensive to reproduce at other sites 
        which use the SELS system.
    </p>
    <p>
        If you have a comment or suggestion, I can be reached at <a href="mailto:alan.p.mccoll@usps.gov">alan.p.mccoll@usps.gov</a>
    </p>
      <p>
        <h3><em>Alan McColl<br/>Electronic Technician<br/>Sandston, VA</em></h3>
      </p> 

            
    </p>
</div>
@section scripts {
<script>
    // using this to call MQTT function which subscribes and then listens for calls
    // this should be changed to something less clunky
    $(document).ready(function() {
        $.ajax({
            type: "POST",
            url: "/Mqtt/Index",
            success: function (response) {
                $(response).each(function() {
                    //console.log("Hello there, I called MQTT .. ");
                })
            },
            failure: function (response) {
                console.log(response.responseText)
            }
        })
    })
</script>
}

Views/Mqtt/CallStatus.cshtml
@{
    Layout = null;
}

    
{
@{
    int counter = ViewBag.mmap.Count;
    @foreach (KeyValuePair<string, int> item in ViewBag.mmap)
        {
            @if (counter > 1)
            {
                <text>"@item.Key": @item.Value, </text>
            }
            else
            {
                <text>"@item.Key": @item.Value } </text>
            }
            counter = counter - 1;
        }
}

Views/Mqtt/CallsFormatted.cshtml
@{
    Layout = null;
}

    
[ @{
    int counter = ViewBag.mmap.Count;
    @foreach (KeyValuePair<string, int> item in ViewBag.mmap)
        {
            @if (counter > 1)
            {
                <text>{"GpioStatus":@item.Value, "Machineid":"@item.Key"}, </text>
            }
            else
            {
                <text>{"GpioStatus":@item.Value, "Machineid":"@item.Key"} </text>
            }
            counter = counter - 1;
    }
} ]

Views/Mqtt/Index.cshtml
@page
@model System.Threading.Tasks.Task

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CallSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/summary_style.css" asp-append-version="true"  /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow /*--mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CallSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calls" asp-action="East">East</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calls" asp-action="West">West</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @* <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div> *@
    <div #main>
        @RenderBody()
    </div>
    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* <script src="~/js/combined.js" asp-append-version="true"></script> *@
    @* <script src="~/js/summary.js" asp-append-version="true"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Time/Index.cshtml
@{
    Layout = null;
}
@DateTime.Now.ToString("hh:mm tt")